display_name: AetherClash

icon: ./assets/images/icon.png

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/po0clash
  - x-scheme-handler/aetherclash

keywords:
  - AetherClash
  - po0-clash
  - Clash
  - ClashMeta
  - Proxy

generic_name: AetherClash

categories:
  - Network

startup_notify: true

include: []